name: Tests

on: [ push, pull_request ]

permissions: read-all

jobs:
    laravel:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: xdebug
                env:
                    COMPOSER_TOKEN: ${{ secrets.COMPOSER_TOKEN }}

            -   name: Install dependencies
                run: composer update --prefer-stable --prefer-dist --no-progress --no-interaction

            -   name: Execute tests
                run: sudo vendor/bin/phpunit --colors=always
